services:
  db:
    image: postgres:14
    env_file: .env
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    networks:
      - backend
    restart: always

  backend:
    image: ghcr.io/lpdalle/backend:v1.1.4
    env_file: .env
    networks:
      - backend
    restart: always

  bot:
    image: ghcr.io/lpdalle/tgbot:v1.0.3
    env_file: .env
    networks:
      - backend
    restart: always

  painter:
    image: ghcr.io/lpdalle/painter:v1.0.5
    env_file: .env
    networks:
      - backend
    restart: always

networks:
  backend:
